use crate::parse::{Component, SignalType};
use crate::render::render_utils::{get_prop_signal_type_param, BuilderCtx};
use convert_case::{Case, Casing};
use proc_macro2::{Ident, TokenStream};
use proc_macro2::{Punct, Spacing};
use quote::quote;

pub fn render_component_macro(ctx: &BuilderCtx, cmp: &Component) -> TokenStream {
    let name: Ident = syn::parse_str(cmp.name.to_string().to_case(Case::Snake).as_str())
        .expect("failed to parse component name");
    let render_fn = syn::parse_str::<Ident>(format!("{}", cmp.render_fn).as_str())
        .expect("failed to parse render fn name");
    let props_name = &ctx.props_name;
    let dollar = Punct::new('$', Spacing::Joint);
    let methods = quote!(#dollar methods);

    let docs = create_generated_macro_docs_section(ctx, cmp, &name);

    // Components with required props finalize through `.build()`, which is where the
    // missing-prop diagnostic fires. Components without keep the 0.4 expansion untouched.
    if ctx.has_required() {
        quote! {
            #docs
            #[macro_export]
            macro_rules! #name {
                ({#dollar(#methods:tt)*}) => {{
                    let applied_props = #props_name::new() #dollar(#methods)* .build();
                    #render_fn (applied_props)
                }}
            }
        }
    } else {
        quote! {
            #docs
            #[macro_export]
            macro_rules! #name {
                ({#dollar(#methods:tt)*}) => {{
                    let default_props = #props_name::new();
                    let applied_props = default_props #dollar(#methods)*;
                    #render_fn (applied_props)
                }}
            }
        }
    }
}

fn create_generated_macro_docs_section(
    ctx: &BuilderCtx,
    cmp: &Component,
    macro_name: &Ident,
) -> TokenStream {
    let mut doc_strings = vec![
        "This macro is generated by the `futures-signals-component-macros` crate.\n".to_string(),
        format!("For more information, see the [{}Props].", cmp.name),
    ];

    if ctx.has_required() {
        let required = ctx
            .required
            .iter()
            .map(|r| format!("`.{}(...)`", r.field))
            .collect::<Vec<_>>()
            .join(", ");

        doc_strings.push(format!(
            "Required props (must be set or the invocation will not compile): {required}\n"
        ));
    }

    doc_strings.extend([
        "All generated methods:\n".to_string(),
        "```rust,ignore".to_string(),
        format!("{}! ({{", macro_name),
    ]);

    for prop in &cmp.props {
        let ty_ = &prop.type_;
        let required_suffix = if prop.is_required { " [required]" } else { "" };

        if let Some(signal) = &prop.is_signal {
            match signal {
                SignalType::Item => {
                    if prop.is_into {
                        doc_strings.push(format!(
                            "    .{}(<impl Into<{}>>){}",
                            prop.name,
                            quote! {#ty_},
                            required_suffix
                        ));
                        doc_strings.push(format!(
                            "    .{}_signal(<Signal<Item = impl Into<{}>>>){}",
                            prop.name,
                            quote! {#ty_},
                            required_suffix
                        ));
                    } else {
                        doc_strings.push(format!(
                            "    .{}(<{}>){}",
                            prop.name,
                            quote! {#ty_},
                            required_suffix
                        ));
                        let ty_ = get_prop_signal_type_param(prop, signal, ty_);
                        doc_strings.push(format!(
                            "    .{}_signal(<{}>){}",
                            prop.name, ty_, required_suffix
                        ));
                    }
                }
                SignalType::Vec => {
                    doc_strings.push(format!(
                        "    .{}(<Into<Vec<{}>>>){}",
                        prop.name,
                        quote! {#ty_},
                        required_suffix
                    ));
                    let ty_ = get_prop_signal_type_param(prop, signal, ty_);
                    doc_strings.push(format!(
                        "    .{}_signal_vec(<{}>){}",
                        prop.name, ty_, required_suffix
                    ));
                }
            }
        } else if prop.is_into {
            doc_strings.push(format!(
                "    .{}(<impl Into<{}>>){}",
                prop.name,
                quote! {#ty_},
                required_suffix
            ));
        } else {
            doc_strings.push(format!(
                "    .{}(<{}>){}",
                prop.name,
                quote! {#ty_},
                required_suffix
            ));
        }
    }

    doc_strings.push("});".to_string());
    doc_strings.push("```".to_string());

    let doc_props = doc_strings
        .into_iter()
        .map(|s| {
            quote! {#[doc = #s]}
        })
        .collect::<Vec<_>>();

    quote! { #(#doc_props)* }
}
